version: '3.4'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_started
    restart: always
    networks:
      - my_network
    volumes:
      - ./client/static:/app/static  # Использование той же локальной директории для статики
      - ./client/templates:/app/templates  # Использование той же локальной директории для шаблонов
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - my_network
    volumes:
      - ./client/static:/app/static  # Монтирование локальной директории для статики
      - ./client/templates:/app/templates  # Монтирование локальной директории для шаблонов
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_DB=twitter
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d twitter -U admin"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./db/:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge
