services:
  db:
    image: postgres:latest
    container_name: test_postgres_container
    environment:
      - POSTGRES_DB=test_twitter
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d test_twitter -U admin" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./init_test_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./test_db/:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - my_network
#    command: /bin/sh -c "pytest -v"  # Запуск pytest с помощью оболочки

networks:
  my_network:
    driver: bridge